language: python
python:
  - 3.6.3

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose2
before_script:
  - psql -c 'CREATE DATABASE test_db;' -U postgres
  - psql -c 'CREATE DATABASE yummy_api;' -U postgres
  - sh travis_db.sh

env:
  DATABASE_URL = 'postgresql://localhost/test_db'
script:
  - nose2 
after_success:
  - coveralls